apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  # Match name of PV
  volumeName: nfs-pv
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
