jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:lABDE8UGK886aMd1tg3n94tAdu8ggttVLA9Bedq47NziKZsVJLJbHcWWSHuCyG3jZDK8O5BWKDvJ5b9Q/tuMaQ==,iv:+KLoMbXqs7E+Jq4T0wqp4yRtru6cAM8rgs+yzvieXzY=,tag:+/tYisKSHmJLABhXNiaFwg==,type:str]
        #ENC[AES256_GCM,data:y4aaj9efeow1FYAQnfM3R/1Md7mPAeBsm64Y9GPcmoTEnV+0vFjsHvLqcGdJo4oyEsqLFnTcPWQqvP4b6jAfoYYBihqeCwMHTF7tB5smlGDPeM3aVba4YxsgsFiOxRZSTg==,iv:/R1huhONAJXn/kdDeaQeNw9omrk9ahAE3OqX7Z7EsQ8=,tag:PAgrAqoz0HAshvI1yXCJUA==,type:comment]
        services:
            grafana:
                apiToken: ENC[AES256_GCM,data:4hhoPQnuKkyHoFgNhTPuuPXdWefFHhFRjhMCny+wC4ztN4IyJqI+6/IYVvl+iW2JdLhcRfhW+yiBLgiUwmkjOA==,iv:3n2xnAYNae0cj8ryD+wj2LA3VMp3F/W4nzGNEvKt6FU=,tag:NwGH09PD9keGuTnGOxR3cA==,type:str]
                url: ENC[AES256_GCM,data:nWdzMh/iICh+WRYEr3g=,iv:vb2GcDb7AzY3383og1lM8izItIyuUm49HFgh9rjfdb8=,tag:a1F5lJhiDyj8ok0D3IESiA==,type:str]
    proxy:
        https:
            letsencrypt:
                contactEmail: ENC[AES256_GCM,data:qIywwuHQQ73PQcvGxlRcIX3wo+ueCjmQJg==,iv:hCTCriyhpFdEhxK2Y9P2EUvrlFWt5j743hfWn+2I35c=,tag:4PJzIn998zXEeKuLBC/wow==,type:str]
        secretToken: ENC[AES256_GCM,data:rshEx6b2qQfQYxZDnmFSVqE35ZcpFrZoCyIKBeI+e0sApresGev3XxzFdVCSmt2LpAf82eZGTnw6vxfExXOWMg==,iv:Nbl5SszrCm72x9momvGsPsrNGpUjn7pKB1gwzm4dXsM=,tag:tcHm4JoFmyeQjPogqfAxGA==,type:str]
    auth:
        type: ENC[AES256_GCM,data:J8fMY/vG,iv:6bmTJ82ZhbJj9391tx9QLr4n/Li/sLHhYdYrQnHznRs=,tag:zHS8V7G6nE1+W4TR4oNdNg==,type:str]
        github:
            clientId: ENC[AES256_GCM,data:jccwgxIXluR+rFHzwxHje3vARdQ=,iv:4ZW4KKDIVqltzuVoaDbncI31MzNBttoj2GpEWuyFvBo=,tag:TFrbtQbtPrs6sntOEhefsA==,type:str]
            clientSecret: ENC[AES256_GCM,data:F++GRNfMdKM8wMBn85arzxal5Eb6n+eETNvFHnB8pSotEdSb3kgZyQ==,iv:ApSvnNBby4pJvFrpin9jU5IhwS98IUrfmFeJaDDcrrM=,tag:jl+CjDTYHwlgcJYYsoHfpQ==,type:str]
            callbackUrl: ENC[AES256_GCM,data:L4pE1qscmn7IMpC5J5fxUHxGqNhmaThQYlP23hx218KX6XgbgntPPPotS52AkYWIPA==,iv:k+uFgfiyEAJ8SFUS+9OzLH8QI8CZbLbgC1Xk8mxi5yc=,tag:ry+NhBXuQyLrlzHq8Spnjw==,type:str]
        admin:
            access: ENC[AES256_GCM,data:o6LtOjU=,iv:UPYdEK61S67NUWzwAdok1nduf3nvNHGZ1mTdNKq5uJ8=,tag:ANxZ036bPwVcTaUUvVzFdA==,type:bool]
            users:
            - ENC[AES256_GCM,data:472dZxlb,iv:FWVDAfD5fzHZqI4uuQxJWvxL9nu9HFqjUIWjVSPab+Y=,tag:HS6uOR3RHv/1rL2ndhASiA==,type:str]
            - ENC[AES256_GCM,data:QLPS7gnPSZx1HS6R,iv:nFWne/f0EQA8aDznsJ1sLj1AqC2RnMS17XMZTi+sb7k=,tag:oDQCdiUbbGBdyosB9Rgpkg==,type:str]
        whitelist:
            users:
            - ENC[AES256_GCM,data:Wy0TQz3ZyXqmJc+Q,iv:U4UgN+oe38Ww2Tp0tmMq5tCcWGGbgvTrkm0D/ORm5xE=,tag:s+siGVLHFii6jPN4JdIlKw==,type:str]
grafana:
    adminUser: ENC[AES256_GCM,data:0nsZxXw=,iv:eTQejIyOkPofBZ9WOVDU2fA8ikFRKOHufqQZxMx4l3M=,tag:8e8C+Hi6u5gfCZ0s4qAHaw==,type:str]
    adminPassword: ENC[AES256_GCM,data:DoMNR1Q4dw==,iv:xWkMBnpaijqcUWeOWr+zi3KTTw8X+uIO3P8wapt9SdU=,tag:5KV0MRBX4oZ/2L5FcrWPDw==,type:str]
    grafana.ini:
        security:
            cookie_secure: ENC[AES256_GCM,data:8pKqCA==,iv:WFicXqUZFrcjxD7bO3VxheiPWxX+ByjNVl8JeBfdy+4=,tag:3QNdwmPAnKWvEMLcTpgB2w==,type:bool]
            secret_key: ENC[AES256_GCM,data:n1axdyQu0rz9NajKiOfF3t9HYfSQ8nw77bkC4xwlAOYahRFY2O5wXA==,iv:X7Q85d9mQ78ofUmppuxFA5jhBh6A+UJO+wsHtcJ3EJo=,tag:oE7zFuENAyS3xuwKuMExOw==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/neurohackademy/locations/global/keyRings/nh-2020/cryptoKeys/main
        created_at: '2020-06-27T10:26:01Z'
        enc: CiQAPiFjYZSksYpBVrkC/69hHvVRPCp53JrETZ/Gh7jmlcwuTxMSSQBLOy9h6SbGThVLMaXfKm26EPKVFXbB8Mrsdhw8nk/W6m17FQE2FL/1DrQKsLbJkcpIken3pDtUMvdsMhnXJWsem4KTZLDQvvw=
    azure_kv: []
    lastmodified: '2020-06-29T18:29:23Z'
    mac: ENC[AES256_GCM,data:u71JOMzQVdiXQGObJSeRV2ELe1Wm+MnE2DM+52cHzQ1jcKsXU5XcqTjyU5PHeAJBE/7yhhbj9nkF9GUCs578N2B2A0dU4jd2ioW0ctANrSUrS/iEAl08RkulbL4PBJVBr9TDGmiglo1CNClY59mHbFREBz5igyNDfb2BS+L3UMc=,iv:Zxyg4fD3XsZmXCIa5oP6mu1j5athbmLT66k4us8i3kg=,tag:AJhnhG+IHB9vBv3ahOkzdw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
