name: nh
channels:
  - conda-forge
dependencies:
  # conda packages for NeuroHackademy
  - git-annex
  - graphviz
  # -------------------------------------------------------------------------

  # Base packages otherwise pinned in repo2docker, by adding them here we get
  # more recent versions such as JupyterLab 2.
  # ref: https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml
  - python=3.7
  - ipywidgets
  - jupyterhub-singleuser
  - jupyterlab
  - nbconvert
  - nbresuse
  - notebook

  - pip
  - pip:
    # pip packages for NeuroHackademy
    - cython
    - dask[complete]
    - datalad
    - nibabel
    - nilearn
    - numba
    - pandas
    - awscli
    - s3fs
    - gcsfs
    - line_profiler
    - memory_profiler
    - graphviz
    - matplotlib
    - mne
    - numpy
    - scipy
    - neuropythy
    - ipyvolume==0.6.0a6
    # -----------------------------------------------------------------------

    # Needed by the neurohackademy Helm chart
    - nbgitpuller
