name: base
channels:
  - conda-forge
dependencies:
  - git-annex
  - pip:
    cython
    dask[complete]
    datalad
    nibabel
    nilearn
    numba
    pandas
    awscli
    s3fs
    gcsfs
    # Admin dependencies
    nbgitpuller
