name: nh
channels:
  - conda-forge
dependencies:
  - git-annex
  # Admin dependencies
  - pip
  - jupyterhub
  - pip:
    - cython
    - dask[complete]
    - datalad
    - nibabel
    - nilearn
    - numba
    - pandas
    - awscli
    - s3fs
    - gcsfs
    # Admin dependencies
    - nbgitpuller
