name: deploy-gke

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job:
# - installs gcloud and configures it to use a GCP SA allowed to decrypt
#   encrypted GCR / GKE credentials
# - installs sops and hubploy
# - use hubploy to build an image and deploys the Helm chart to GKE
jobs:
  deploy-gke:
    # Available runners: https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
    # Ubuntu 18.04 documentation: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Install SOPS and hubploy
      run: |
        curl -sSL https://github.com/mozilla/sops/releases/download/v3.5.0/sops_3.5.0_amd64.deb -o /tmp/sops.deb
        sudo apt-get install /tmp/sops.deb
        pip install https://github.com/yuvipanda/hubploy/archive/master.zip
    - name: "hubploy: build"
      run: |
        hubploy build hub.neurohackademy.org --push
    - name: "hubploy: deploy"
      run: |
        hubploy deploy --namespace default --cleanup-on-fail hub.neurohackademy.org chart prod
